spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

    #DRUID 专用配置
    initialSize: 5
    minIdle: 5
    maxActice: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000

    #配置监控统计拦截器filters,stat 监控统计 log4j 日志记录 wall 防御sql注入
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
